name: quad_engine
description: A lightweight graphics library written in dart. Designed for the fast creation of a wide range of applications.
version: 1.0.0
repository: https://github.com/jamesmckubre/Quad-Engine

platforms:
  web:

environment:
  sdk: ^3.2.6

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
